Allow 12-hour clock format in the status line
arcticicestudio/nord-tmux pull request #50
Opened 2020-08-07 03:50 UTC by perryjiang

Sets the status line's time format to match the value of the
`clock-mode-style` global option.

<img width="1680" alt="Screen Shot 2020-08-06 at 11 48 33 PM" src="https://user-images.githubusercontent.com/12715169/89606973-5ba06900-d83f-11ea-8421-96083a651870.png">

Refs #24

2020-08-20 18:59 UTC, svengreb requested changes
Just added a small suggestion.

2020-08-20 18:59 UTC, svengreb commented on nord.tmux
> +  if [ $(tmux show-option -gqv "clock-mode-style") == '12' ]; then
We should [quote the sub-shell call to prevent word splitting][ss].

```suggestion
  if [ "$(tmux show-option -gqv "clock-mode-style")" == '12' ]; then
```

[ss]: https://github.com/koalaman/shellcheck/wiki/SC2046

2020-08-20 19:00 UTC, arcticicestudio approved these changes
Hi @perryjiang :wave:, thanks for your contribution :+1:

LGTM :rocket:
Contributions like this are always a great help, issues like #24 are unfortunately stale for too long due to my limited free time and when no PRs like yours are submitted.
I'll merge it when the review suggestion has been resolved to ensure it'll be included in the next release version.

2020-08-23 17:13 UTC, perryjiang commented on nord.tmux
> +  if [ $(tmux show-option -gqv "clock-mode-style") == '12' ]; then
Done!

2020-08-25 18:50 UTC, svengreb approved these changes
LGTM now, thanks again for your contribution 🚀

2020-08-25 18:54 UTC, merged

2020-08-25 18:56 UTC, arcticicestudio commented
###### Release Note Assets

<p align="center"><strong>12-hour</strong> clock format</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/91215883-60a55980-e715-11ea-94de-42042c31e987.png" /></p>

<p align="center"><strong>24-hour</strong> clock format</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/91215889-61d68680-e715-11ea-86ff-a516b56370f8.png" /></p>